services:
  redis:
    image: redis:7
    container_name: shopping-redis
    ports:
      - "16379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    restart: always
    networks:
      - shopping-network

  mysql:
    image: mysql:8.0.32
    container_name: shopping-mysql
    ports:
      - "13306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: zjx123456
    volumes:
      - ./DB/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./DB/sql:/docker-entrypoint-initdb.d
      - ./DB/data:/var/lib/mysql
    restart: always
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge